#ifndef VW_CRYPTO_H
#define VW_CRYPTO_H

/*
 * vw_crypto — cryptographic primitives for VaporWault.
 *
 * Wraps mbedTLS (SHA-256, CSPRNG) and the vendored Argon2id reference
 * implementation. All functions are thread-safe.
 */

#include "vw_proto.h"   /* vw_err_t, VW_HASH_BYTES */
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Secure memory zeroing ───────────────────────────────────────────────── */

static inline void vw_crypto_secure_zero(void *p, size_t n) {
    volatile unsigned char *vp = (volatile unsigned char *)p;
    while (n--) *vp++ = 0;
}

/* ── Constants ───────────────────────────────────────────────────────────── */

#define VW_ARGON2_SALT_BYTES      16u
#define VW_ARGON2_HASH_BYTES      32u

/* OWASP 2023 Argon2id recommended minimums */
#define VW_ARGON2_TIME_COST       3u
#define VW_ARGON2_MEM_KB          65536u   /* 64 MiB */
#define VW_ARGON2_PARALLELISM     4u

/* TOTP window: ±1 interval of 30 seconds */
#define VW_TOTP_INTERVAL_SECS     30u
#define VW_TOTP_WINDOW            1u
#define VW_TOTP_DIGITS            6u

/* AES-256-GCM (TASK-099 vault content/key-wrap encryption) */
#define VW_AES_GCM_KEY_BYTES      32u
#define VW_AES_GCM_NONCE_BYTES    12u
#define VW_AES_GCM_TAG_BYTES      16u

/*
 * Vault Argon2id KDF (TASK-099): derives the KEK that wraps a vault's VK
 * from the user's Encryption Passphrase. Distinct threat model from the
 * login-token Argon2id above (VW_ARGON2_*): this KDF must resist an
 * *offline* attack against an exfiltrated wrapped-VK blob, since a
 * compromised server is explicitly in-scope for E2EE. Floor pinned by
 * SEC.07 (docs/PROTOCOL.md §7.11.5) — callers may exceed it, never go
 * below it. `parallelism` must be exactly 1 (not merely >= 1): higher
 * parallelism splits Argon2id's memory into independent lanes, which
 * *reduces* effective memory-hardness against a parallel (GPU/ASIC)
 * attacker for a fixed total memory budget.
 */
#define VW_VAULT_KDF_SALT_BYTES        16u
#define VW_VAULT_KEK_BYTES             32u
#define VW_VAULT_ARGON2_MIN_MEM_KB     19456u  /* 19 MiB floor */
#define VW_VAULT_ARGON2_MIN_TIME_COST  2u
#define VW_VAULT_ARGON2_PARALLELISM    1u

/* ── Initialisation ─────────────────────────────────────────────────────── */

/*
 * Initialise the mbedTLS entropy and CSPRNG contexts. Must be called
 * once before any other vw_crypto function. Not thread-safe; call from
 * main() before spawning threads.
 */
vw_err_t vw_crypto_init(void);

/*
 * Release resources allocated by vw_crypto_init().
 */
void vw_crypto_cleanup(void);

/* ── SHA-256 ─────────────────────────────────────────────────────────────── */

/*
 * Hash len bytes of data. out_hash must be VW_HASH_BYTES (32) bytes.
 */
vw_err_t vw_crypto_sha256(const void *data, size_t len,
                           uint8_t out_hash[VW_HASH_BYTES]);

/*
 * Platform-agnostic file handle for vw_crypto_sha256_file.
 * Win32: HANDLE is typedef void* — we use void* to avoid pulling in <windows.h>.
 * POSIX: a file descriptor (int).
 */
#ifdef _WIN32
typedef void *vw_file_handle_t;
#else
typedef int   vw_file_handle_t;
#endif

/*
 * Streaming SHA-256 over a file. Reads from the current position to EOF.
 * out_hash must be VW_HASH_BYTES (32) bytes.
 */
vw_err_t vw_crypto_sha256_file(vw_file_handle_t fh, uint8_t out_hash[VW_HASH_BYTES]);

/* ── CRC-32 ──────────────────────────────────────────────────────────────── */
/* NOT a cryptographic primitive; do not use for MACs or security integrity
 * checks. Use vw_crypto_hmac_sha256 for authenticated integrity. */

/*
 * Compute CRC32 (ISO 3309 / Ethernet polynomial 0xEDB88320) over data[0..len-1].
 * Does NOT require vw_crypto_init(). Thread-safe.
 */
uint32_t vw_crypto_crc32(const void *data, size_t len);

/*
 * Incremental CRC32: continue a running CRC over an additional chunk.
 * Pass prev_crc=0 for the first chunk.
 * vw_crypto_crc32(d, n) == vw_crypto_crc32_update(0, d, n).
 * Does NOT require vw_crypto_init(). Thread-safe.
 */
uint32_t vw_crypto_crc32_update(uint32_t prev_crc, const void *data, size_t len);

/* ── CSPRNG ─────────────────────────────────────────────────────────────── */

/*
 * Fill buf with len cryptographically secure random bytes.
 * Uses mbedTLS CTR-DRBG seeded from the platform entropy source.
 */
vw_err_t vw_crypto_random(void *buf, size_t len);

/* ── Argon2id ────────────────────────────────────────────────────────────── */

/*
 * Hash a password with Argon2id.
 *
 *   salt == NULL : generate a random salt; out_salt receives the generated bytes
 *                  and must not be NULL.
 *   salt != NULL : use the caller-provided salt; out_salt is ignored and may be NULL.
 *
 *   password / pw_len : raw password bytes (not null-terminated)
 *   out_hash          : VW_ARGON2_HASH_BYTES output buffer (always written)
 */
vw_err_t vw_crypto_argon2id_hash(const void *password, size_t pw_len,
                                  const uint8_t *salt,
                                  uint8_t out_salt[VW_ARGON2_SALT_BYTES],
                                  uint8_t out_hash[VW_ARGON2_HASH_BYTES]);

/*
 * Verify a password against a stored hash+salt in constant time.
 * Returns VW_OK if the password matches, VW_ERR_AUTH_BAD_CREDS otherwise.
 */
vw_err_t vw_crypto_argon2id_verify(const uint8_t hash[VW_ARGON2_HASH_BYTES],
                                    const uint8_t salt[VW_ARGON2_SALT_BYTES],
                                    const void *password, size_t pw_len);

/* ── Vault Argon2id KDF (TASK-099) ──────────────────────────────────────── */

/*
 * Explicit Argon2id parameters for the vault KEK derivation. Deliberately
 * a distinct type from vw_crypto_argon2id_hash's implicit/hardcoded
 * VW_ARGON2_* constants — see the SEC.07 guardrail note above
 * vw_crypto_vault_derive_kek: this struct's presence in the signature
 * makes it impossible to pass this KDF's inputs to the login KDF (or vice
 * versa) without a compile error, so the two derivation paths cannot be
 * pointer-substituted or copy-pasted into each other unnoticed.
 */
typedef struct {
    uint32_t mem_cost_kib;
    uint32_t time_cost;
    uint32_t parallelism;
} vw_vault_kdf_params_t;

/*
 * Derive a vault KEK from an Encryption Passphrase. NOT the same code path
 * as vw_crypto_argon2id_hash/_verify (login token derivation) — see the
 * struct doc comment above and docs/PROTOCOL.md §7.11.5. Rejects params
 * that fall below the pinned floor (VW_VAULT_ARGON2_MIN_MEM_KB/
 * _MIN_TIME_COST) or that don't set parallelism == VW_VAULT_ARGON2_PARALLELISM
 * with VW_ERR_INVALID_ARG, so a corrupted or tampered kdf_params blob
 * (read back from the server, which stores it opaquely) can never
 * silently weaken the derivation.
 */
vw_err_t vw_crypto_vault_derive_kek(const void *passphrase, size_t passphrase_len,
                                     const uint8_t salt[VW_VAULT_KDF_SALT_BYTES],
                                     const vw_vault_kdf_params_t *params,
                                     uint8_t out_kek[VW_VAULT_KEK_BYTES]);

/* ── AES-256-GCM (TASK-099) ──────────────────────────────────────────────── */

/*
 * Encrypt len bytes of plaintext with AES-256-GCM. key must be
 * VW_AES_GCM_KEY_BYTES, nonce must be VW_AES_GCM_NONCE_BYTES and MUST NOT
 * be reused with the same key (caller's responsibility — see
 * vw_crypto_vault_chunk_nonce for the deterministic per-chunk scheme this
 * project uses for content encryption). aad/aad_len may be NULL/0.
 * out_ciphertext must be at least len bytes; may alias plaintext.
 * out_tag must be VW_AES_GCM_TAG_BYTES.
 */
vw_err_t vw_crypto_aes256gcm_encrypt(const uint8_t key[VW_AES_GCM_KEY_BYTES],
                                      const uint8_t nonce[VW_AES_GCM_NONCE_BYTES],
                                      const void *aad, size_t aad_len,
                                      const void *plaintext, size_t len,
                                      uint8_t *out_ciphertext,
                                      uint8_t out_tag[VW_AES_GCM_TAG_BYTES]);

/*
 * Decrypt and verify len bytes of ciphertext with AES-256-GCM. Must NOT
 * alias ciphertext with out_plaintext (mbedTLS restriction). On
 * authentication failure returns VW_ERR_CRYPTO and zeroes out_plaintext —
 * callers must not use out_plaintext's contents unless VW_OK is returned.
 * A generic VW_ERR_CRYPTO is returned rather than a more specific code
 * because this primitive doesn't know its caller's context (VK-unwrap
 * under a wrong passphrase vs. corrupted/tampered chunk content look
 * identical here); callers add that semantic meaning at their own layer.
 */
vw_err_t vw_crypto_aes256gcm_decrypt(const uint8_t key[VW_AES_GCM_KEY_BYTES],
                                      const uint8_t nonce[VW_AES_GCM_NONCE_BYTES],
                                      const void *aad, size_t aad_len,
                                      const void *ciphertext, size_t len,
                                      const uint8_t tag[VW_AES_GCM_TAG_BYTES],
                                      uint8_t *out_plaintext);

/*
 * Deterministic per-chunk nonce derivation for vault content encryption
 * (docs/PROTOCOL.md §7.11.3): nonce = HKDF-SHA256(ikm=dek, salt=NULL,
 * info="vw-chunk-nonce" || chunk_index as 8-byte LE)[0:12].
 *
 * This is the mandatory, SEC.07-revised scheme — deterministic from
 * (dek, chunk_index) alone, NOT random-prefix+counter — specifically to
 * make nonce reuse impossible across an interrupted-and-retried upload:
 * re-encrypting chunk index i with the same dek always derives the exact
 * same nonce, and since a fresh dek is required per file/version (never
 * reused), the (key, nonce) pair as a whole is never reused across
 * distinct plaintexts.
 */
vw_err_t vw_crypto_vault_chunk_nonce(const uint8_t dek[VW_AES_GCM_KEY_BYTES],
                                      uint64_t chunk_index,
                                      uint8_t out_nonce[VW_AES_GCM_NONCE_BYTES]);

/* ── HMAC-SHA256 ─────────────────────────────────────────────────────────── */

/*
 * Compute HMAC-SHA256 over data[0..data_len-1] using key[0..key_len-1].
 * out_mac must be VW_HASH_BYTES (32) bytes.
 */
vw_err_t vw_crypto_hmac_sha256(const uint8_t *key, size_t key_len,
                                const void *data, size_t data_len,
                                uint8_t out_mac[VW_HASH_BYTES]);

/* ── Timing-safe comparison ──────────────────────────────────────────────── */

/*
 * Compare len bytes of a and b in constant time (no short-circuit).
 * Returns 1 if equal, 0 if not. Use for token and hash comparison.
 */
int vw_crypto_constant_time_eq(const void *a, const void *b, size_t len);

/* ── HOTP / TOTP ─────────────────────────────────────────────────────────── */

/*
 * Generate a VW_TOTP_DIGITS-digit HOTP code using HMAC-SHA1.
 *   key      : secret key bytes
 *   key_len  : key length in bytes
 *   counter  : 8-byte counter (for TOTP: Unix time / VW_TOTP_INTERVAL_SECS)
 *   out_code : 6-digit decimal code written as a null-terminated string
 */
vw_err_t vw_crypto_hotp(const uint8_t *key, size_t key_len,
                         uint64_t counter,
                         char out_code[VW_TOTP_DIGITS + 1]);

/*
 * Verify a TOTP code for the given key at the given Unix timestamp.
 * Checks the current window ± VW_TOTP_WINDOW intervals to allow clock skew.
 * Returns VW_OK if valid, VW_ERR_AUTH_2FA_INVALID otherwise.
 */
vw_err_t vw_crypto_totp_verify(const uint8_t *key, size_t key_len,
                                int64_t unix_time,
                                const char *code);

/* ── Hex encoding ────────────────────────────────────────────────────────── */

/*
 * Encode len bytes of src as lowercase hex into dst.
 * dst must be at least len*2+1 bytes. Null-terminates the output.
 */
void vw_crypto_hex_encode(const uint8_t *src, size_t len, char *dst);

/*
 * Decode a hex string of hex_len characters into dst.
 * hex_len must be even. Returns VW_ERR_INVALID_ARG on malformed input.
 */
vw_err_t vw_crypto_hex_decode(const char *hex, size_t hex_len, uint8_t *dst);

#ifdef __cplusplus
}
#endif

#endif /* VW_CRYPTO_H */
